"""add github identity to users

Revision ID: 12097b55786a
Revises: 947654afcf0d
Create Date: 2026-09-26 14:45:37.521723

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12097b55786a"
down_revision: Union[str, Sequence[str], None] = "947654afcf0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("github_id", sa.String(length=100), nullable=True))
    op.add_column(
        "users", sa.Column("github_login", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("github_access_token", sa.String(length=512), nullable=True)
    )
    op.create_unique_constraint("uq_users_github_id", "users", ["github_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("uq_users_github_id", "users", type_="unique")
    op.drop_column("users", "github_access_token")
    op.drop_column("users", "github_login")
    op.drop_column("users", "github_id")
    # ### end Alembic commands ###
