"""add risk_findings table

Revision ID: 217015d9942a
Revises: d7c86d75d7b7
Create Date: 2026-09-29 12:40:54.777160

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "217015d9942a"
down_revision: Union[str, Sequence[str], None] = "d7c86d75d7b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("symbol_id", sa.UUID(), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column(
            "features_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["project_repositories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_risk_findings_repo_id", "risk_findings", ["repo_id"], unique=False
    )
    op.create_index(
        "ix_risk_findings_repo_level",
        "risk_findings",
        ["repo_id", "risk_level"],
        unique=False,
    )
    op.create_index(
        "ix_risk_findings_symbol_id", "risk_findings", ["symbol_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_risk_findings_symbol_id", table_name="risk_findings")
    op.drop_index("ix_risk_findings_repo_level", table_name="risk_findings")
    op.drop_index("ix_risk_findings_repo_id", table_name="risk_findings")
    op.drop_table("risk_findings")
    # ### end Alembic commands ###
