"""drop risk_findings table

Revision ID: 2c35e0edd4ef
Revises: 71d9b12a053c
Create Date: 2026-09-29 17:23:47.840494

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2c35e0edd4ef"
down_revision: Union[str, Sequence[str], None] = "71d9b12a053c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_findings_repo_id"), table_name="risk_findings")
    op.drop_index(op.f("ix_risk_findings_repo_level"), table_name="risk_findings")
    op.drop_index(op.f("ix_risk_findings_symbol_id"), table_name="risk_findings")
    op.drop_table("risk_findings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_findings",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repo_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("symbol_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "risk_level", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column(
            "probability",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "features_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "model_version", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["project_repositories.id"],
            name=op.f("risk_findings_repo_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["symbols.id"],
            name=op.f("risk_findings_symbol_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("risk_findings_pkey")),
    )
    op.create_index(
        op.f("ix_risk_findings_symbol_id"), "risk_findings", ["symbol_id"], unique=False
    )
    op.create_index(
        op.f("ix_risk_findings_repo_level"),
        "risk_findings",
        ["repo_id", "risk_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_findings_repo_id"), "risk_findings", ["repo_id"], unique=False
    )
    # ### end Alembic commands ###
