"""add mode column to analysis_jobs

Revision ID: 71d9b12a053c
Revises: 217015d9942a
Create Date: 2026-09-29 15:55:52.100618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71d9b12a053c"
down_revision: Union[str, Sequence[str], None] = "217015d9942a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_jobs",
        sa.Column("mode", sa.String(length=20), nullable=False, server_default="full"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_jobs", "mode")
    # ### end Alembic commands ###
