"""add structural analysis tables

Revision ID: a6dac032b9b5
Revises: 79b4d93cb86f
Create Date: 2026-09-26 15:44:58.300896

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6dac032b9b5"
down_revision: Union[str, Sequence[str], None] = "79b4d93cb86f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=64), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["project_repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "path", name="uq_files_repo_path"),
    )
    op.create_index("ix_files_repo_id", "files", ["repo_id"], unique=False)
    op.create_table(
        "edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("source_kind", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("edge_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["project_repositories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["target_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_edges_repo_id_type", "edges", ["repo_id", "edge_type"], unique=False
    )
    op.create_index("ix_edges_source", "edges", ["source_id"], unique=False)
    op.create_index("ix_edges_target", "edges", ["target_id"], unique=False)
    op.create_table(
        "imports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=1024), nullable=False),
        sa.Column("is_relative", sa.Boolean(), nullable=False),
        sa.Column("resolved_path", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["project_repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_imports_repo_id", "imports", ["repo_id"], unique=False)
    op.create_table(
        "symbols",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["project_repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_symbols_file_id", "symbols", ["file_id"], unique=False)
    op.create_index(
        "ix_symbols_repo_id_kind", "symbols", ["repo_id", "kind"], unique=False
    )
    op.add_column(
        "analysis_jobs",
        sa.Column(
            "symbols_indexed",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_jobs", "symbols_indexed")
    op.drop_index("ix_symbols_repo_id_kind", table_name="symbols")
    op.drop_index("ix_symbols_file_id", table_name="symbols")
    op.drop_table("symbols")
    op.drop_index("ix_imports_repo_id", table_name="imports")
    op.drop_table("imports")
    op.drop_index("ix_edges_target", table_name="edges")
    op.drop_index("ix_edges_source", table_name="edges")
    op.drop_index("ix_edges_repo_id_type", table_name="edges")
    op.drop_table("edges")
    op.drop_index("ix_files_repo_id", table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
